#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["click>=8"]
# ///
"""Bootstrap the containerized BauernKarte dev environment.

See bootstrap.md for details and prerequisites. The shebang above runs
this under `uv run --script`, which reads the inline `dependencies` block
and installs/caches `click` into an ephemeral venv on the fly — no
pre-installed `click` or manual venv needed, as long as `uv` itself is on
PATH (https://docs.astral.sh/uv/guides/scripts/). Run it either as
`./bootstrap.py system` (uv via the shebang) or `uv run bootstrap.py
system`; `python3 bootstrap.py system` also still works if `click`
happens to already be installed, just without uv managing that for you.

Everything is driven by `.env`: no credentials are hardcoded here beyond
the defaults `env` writes into that file, and docker-compose.yml
interpolates the same keys. Change a DB_* value there and every
subcommand follows.

Subcommands:
    env     write `.env` with dev defaults
    db      start the compose `db` service + `sqlx migrate run`
    app     `cargo sqlx prepare` + build/start the compose `app` service
    system  db, then app
    stores  seed OSM shop=farm data into the running db

Usage:
    ./bootstrap.py env
    ./bootstrap.py system
    ./bootstrap.py stores
"""

import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from urllib.parse import quote

import click

REPO_ROOT = Path(__file__).resolve().parent
ENV_FILE = REPO_ROOT / ".env"
SEED_SCRIPT = REPO_ROOT / "scripts" / "seed_osm_farm_shops.py"

CARGO_BIN = Path.home() / ".cargo" / "bin"

# Name of the Postgres service in docker-compose.yml, and the port it
# listens on *inside* the compose network (DB_PORT is the host-side
# publish of that same port).
DB_SERVICE = "db"
DB_SERVICE_PORT = "5432"
APP_SERVICE = "app"

# Dev defaults for `.env`. The DB_* values are the single source of
# truth for credentials — DATABASE_URL below is derived from them, and
# docker-compose.yml interpolates them directly.
DEFAULTS = {
    "DB_USER": "bauernkarte",
    "DB_PWD": "dev",
    "DB_NAME": "bauernkarte",
    "DB_HOST": "127.0.0.1",
    "DB_PORT": "5434",
    "APP_PORT": "3000",
    "BIND_ADDR": "0.0.0.0:3000",
    "ADMIN_PASSWORD": "bitte-hier-aendern-2026",
    "SECURE_COOKIES": "false",
    "RUST_LOG": "bauernkarte=debug,tower_http=debug",
}

ENV_TEMPLATE = """\
# Generated by `./bootstrap.py env` — dev-only values, safe to edit.
#
# Read by three things: docker-compose.yml (compose auto-loads this file
# for `${{VAR}}` interpolation), bootstrap.py, and the app itself.

# --- database ----------------------------------------------------------
# The credentials. docker-compose.yml passes these straight to the `db`
# service as POSTGRES_USER/PASSWORD/DB, so changing one here changes it
# everywhere (an existing pgdata volume keeps the old ones though — see
# "Resetting" in bootstrap.md).
DB_USER={DB_USER}
DB_PWD={DB_PWD}
DB_NAME={DB_NAME}
# How the *host* reaches Postgres: DB_PORT is the port compose publishes
# for the `db` service. Containers use `db:{DB_SERVICE_PORT}` instead.
DB_HOST={DB_HOST}
DB_PORT={DB_PORT}

# Derived from the DB_* values above, for host-side tooling: `sqlx
# migrate run`, `cargo sqlx prepare` and a host-side `cargo run`.
# Re-run `./bootstrap.py env --force` after changing any DB_* value.
DATABASE_URL={DATABASE_URL}

# --- admin -------------------------------------------------------------
# Password for the seeded admin account (bauernkarte@rehka.dev). Applied
# once, on the first startup that finds the account without a password —
# a change made later through the app is not overwritten. Must satisfy
# the same policy as any other password (see the register form).
ADMIN_PASSWORD={ADMIN_PASSWORD}

# --- app ---------------------------------------------------------------
# Host port the `app` container publishes (container-side it's always
# 3000). BIND_ADDR applies to a host-side `cargo run`.
APP_PORT={APP_PORT}
BIND_ADDR={BIND_ADDR}
# `false`: nothing terminates TLS in front of the app, and a `Secure`
# session cookie over plain HTTP makes login silently fail. Set `true`
# once a TLS-terminating proxy sits in front of it.
SECURE_COOKIES={SECURE_COOKIES}
RUST_LOG={RUST_LOG}
"""


def run(cmd, **kwargs):
    click.echo(f"$ {' '.join(cmd)}")
    kwargs.setdefault("check", True)
    return subprocess.run(cmd, **kwargs)


def require(cmd_name, path, hint):
    if shutil.which(cmd_name, path=path) is None:
        raise click.ClickException(f"`{cmd_name}` not found on PATH. {hint}")


def compose_cmd():
    """The compose implementation to drive: docker's v2 subcommand, or
    a standalone podman-compose/docker-compose binary."""
    if shutil.which("docker"):
        probe = subprocess.run(
            ["docker", "compose", "version"], capture_output=True
        )
        if probe.returncode == 0:
            return ["docker", "compose"]
    for exe in ("podman-compose", "docker-compose"):
        if shutil.which(exe):
            return [exe]
    raise click.ClickException(
        "no compose implementation found — install podman-compose, or "
        "docker with the compose plugin."
    )


def database_url(cfg, host, port):
    """Build a connection string from `.env`'s credentials for a given
    host/port — the host-published one for tooling running on the host,
    `db:5432` for anything running inside the compose network."""
    user = quote(cfg["DB_USER"], safe="")
    pwd = quote(cfg["DB_PWD"], safe="")
    return f"postgres://{user}:{pwd}@{host}:{port}/{cfg['DB_NAME']}"


def render_env(values):
    values = dict(values)
    values["DB_SERVICE_PORT"] = DB_SERVICE_PORT
    values["DATABASE_URL"] = database_url(
        values, values["DB_HOST"], values["DB_PORT"]
    )
    return ENV_TEMPLATE.format(**values)


def load_env():
    """Parse `.env` into a dict, and re-derive DATABASE_URL from the
    DB_* keys so they stay the single source of truth."""
    if not ENV_FILE.exists():
        raise click.ClickException(
            f"{ENV_FILE.name} is missing — run `./bootstrap.py env` first."
        )
    cfg = {}
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        cfg[key.strip()] = value.strip().strip('"').strip("'")

    missing = [k for k in DEFAULTS if k not in cfg]
    if missing:
        raise click.ClickException(
            f"{ENV_FILE.name} is missing {', '.join(missing)} — it predates "
            "the DB_*-based layout. Back it up and re-run "
            "`./bootstrap.py env --force`."
        )

    derived = database_url(cfg, cfg["DB_HOST"], cfg["DB_PORT"])
    if cfg.get("DATABASE_URL") != derived:
        click.echo(
            f"warning: {ENV_FILE.name}'s DATABASE_URL doesn't match its DB_* "
            f"values. Using {derived}; run `./bootstrap.py env --force` to "
            "rewrite the file (a host-side `cargo run` reads the stale one).",
            err=True,
        )
    cfg["DATABASE_URL"] = derived
    return cfg


def compose_env(cfg):
    """Environment for compose calls: real env vars take precedence over
    `.env` during interpolation, so passing the parsed values through
    makes this work the same on implementations that don't read `.env`
    themselves."""
    return {**os.environ, **cfg}


def cargo_env(cfg):
    """cargo/rustc/sqlx aren't on the default PATH on every machine;
    prepend ~/.cargo/bin like the rest of local dev does."""
    env = {**os.environ, "DATABASE_URL": cfg["DATABASE_URL"]}
    if str(CARGO_BIN) not in env.get("PATH", ""):
        env["PATH"] = f"{CARGO_BIN}{os.pathsep}{env.get('PATH', '')}"
    return env


def db_is_ready(compose, cfg):
    return subprocess.run(
        compose + ["exec", "-T", DB_SERVICE, "pg_isready",
                   "-U", cfg["DB_USER"], "-d", cfg["DB_NAME"]],
        capture_output=True, env=compose_env(cfg),
    ).returncode == 0


def wait_for_db(compose, cfg, timeout=90):
    click.echo("waiting for postgres to accept connections...")
    deadline = time.time() + timeout
    while time.time() < deadline:
        if db_is_ready(compose, cfg):
            click.echo("postgres is ready")
            return
        time.sleep(1)
    raise click.ClickException(
        f"postgres did not become ready within {timeout}s "
        f"(check `{' '.join(compose)} logs {DB_SERVICE}`)"
    )


def require_running_db(compose, cfg):
    if not db_is_ready(compose, cfg):
        raise click.ClickException(
            f"the `{DB_SERVICE}` service isn't up and accepting connections "
            "— run `./bootstrap.py db` first."
        )


def do_env(force):
    if ENV_FILE.exists() and not force:
        click.echo(f"{ENV_FILE.name} already exists, leaving it alone "
                   "(pass --force to overwrite)")
        return
    ENV_FILE.write_text(render_env(DEFAULTS))
    click.echo(f"wrote {ENV_FILE.name} with dev defaults")


def do_db():
    do_env(force=False)
    cfg = load_env()
    compose = compose_cmd()

    run(compose + ["up", "-d", DB_SERVICE], env=compose_env(cfg))
    wait_for_db(compose, cfg)

    env = cargo_env(cfg)
    require("sqlx", env["PATH"],
            "install it with: cargo install sqlx-cli --no-default-features "
            "--features postgres")
    click.echo(f"applying migrations against {cfg['DATABASE_URL']}")
    run(["sqlx", "migrate", "run"], cwd=REPO_ROOT, env=env)
    click.echo("db ready.")


def do_app():
    cfg = load_env()
    compose = compose_cmd()
    require_running_db(compose, cfg)

    env = cargo_env(cfg)
    require("cargo", env["PATH"], "install Rust: https://rustup.rs")
    require("cargo-sqlx", env["PATH"],
            "install it with: cargo install sqlx-cli --no-default-features "
            "--features postgres")

    # Refreshes the checked-in `.sqlx/` query cache against the live,
    # migrated database. The image build sets SQLX_OFFLINE=true (see
    # Dockerfile) because no database is reachable during a build, so
    # this has to happen here, before the build, or the macros'd query
    # checks go stale.
    click.echo("regenerating the .sqlx/ offline query cache...")
    run(["cargo", "sqlx", "prepare"], cwd=REPO_ROOT, env=env)

    run(compose + ["up", "-d", "--build", APP_SERVICE], env=compose_env(cfg))
    click.echo()
    click.echo(f"app is up on http://127.0.0.1:{cfg['APP_PORT']}")


def do_stores():
    """Seed the db with OpenStreetMap shop=farm data (design.md's public
    reference data, see scripts/seed_osm_farm_shops.py's own docstring
    for the field mapping/provenance)."""
    cfg = load_env()
    compose = compose_cmd()
    require_running_db(compose, cfg)
    if not SEED_SCRIPT.exists():
        raise click.ClickException(f"{SEED_SCRIPT} is missing")

    # `--live`: the seed script's own default (fetch-vs-replay-stdin
    # picked from whether *its* stdin is a tty) only works run directly
    # in a terminal — this subprocess's stdin isn't a tty regardless of
    # how bootstrap.py itself was invoked, so `--live` forces the fetch
    # explicitly instead of relying on that.
    click.echo("fetching OSM shop=farm data from Overpass and generating "
               "seed SQL (this hits a public API and can take a minute or "
               "two)...")
    try:
        seed = subprocess.run(
            [sys.executable, str(SEED_SCRIPT), "--live"],
            cwd=REPO_ROOT, capture_output=True, text=True, check=True,
        )
    except subprocess.CalledProcessError as exc:
        raise click.ClickException(f"seed script failed:\n{exc.stderr}")
    if seed.stderr:
        click.echo(seed.stderr.strip())

    # Applied by `psql` inside the already-running `db` container rather
    # than a throwaway one or a host `psql` install: the image ships a
    # client, so nothing extra needs pulling or installing. The URL is
    # the container-side view of the same `.env` credentials.
    click.echo(f"applying seed SQL to {cfg['DB_NAME']} via the "
               f"`{DB_SERVICE}` container...")
    run(
        compose + ["exec", "-T", DB_SERVICE, "psql",
                   database_url(cfg, "127.0.0.1", DB_SERVICE_PORT),
                   "-v", "ON_ERROR_STOP=1", "-q"],
        input=seed.stdout, text=True, env=compose_env(cfg),
    )
    click.echo("stores seeded.")


@click.group()
def cli():
    """Bootstrap the containerized BauernKarte dev environment."""


@cli.command()
@click.option("--force", is_flag=True, help="Overwrite an existing .env.")
def env(force):
    """Write .env with dev defaults."""
    do_env(force)


@cli.command()
def db():
    """Start the `db` container and run migrations."""
    do_db()


@cli.command()
def app():
    """`cargo sqlx prepare`, then build/start the `app` container."""
    do_app()


@cli.command()
def system():
    """db, then app."""
    do_db()
    do_app()


@cli.command()
def stores():
    """Seed OSM shop=farm data into the running db."""
    do_stores()


if __name__ == "__main__":
    cli()
